version: '3.9'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8089:80
        links:
            - php_server
    php_server:
        container_name: php_server
        build: .
        volumes:
            - ./nginx:/usr/share/nginx/html
            - project:/var/www/html/src
        ports: 
        - '8001:8001'
    mysql:
        container_name: mysqldb
        image: mysql:latest
        ports:
           - 3306:3306
        volumes:
            - ./:/usr/share/nginx/html
            - ./database/mysql-data:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=lumen
            - MYSQL_PASSWORD=lumenpwd
            - MYSQL_DATABASE=mydb
    mailhog_server:
        image: mailhog/mailhog
        container_name: mailhog_server
        #this is optional
        tty: true
        ports:
            - '1025:1025'
            - '8025:8025'

volumes:
    project:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './src'
